### ISSUE TITLE
Video demostration

### ISSUE THREAD

**Issue by johnfelipe** [RalfKoban/MiKo-Analyzers#527]
Is possible create a video with demostration?

**Comment by RalfKoban** [comment]
Why a video? What should it demonstrate?

**Comment by johnfelipe** [comment]
Is for a build in my side a good documentation
May be a gif animated too...

**Comment by RalfKoban** [comment]
What information is missing in the documentation?

**Comment by johnfelipe** [comment]
Is for a rookie users like me
I'm already use sonarqube
But I want use your analyzer
Pls help me with a video or gif animated for how use it
Tnks.

**Comment by RalfKoban** [comment]
It's an extension to Visual Studio.

How to install such analyzers is described here:
https://learn.microsoft.com/en-us/visualstudio/code-quality/install-roslyn-analyzers?view=vs-2022

Screenshots on how to use such analyzer are available here:
https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022
